config/routes.rb
Rails.application.routes.draw do

  resources :categories
  root to: 'static#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :users
  resources :recommendations do
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# class Category < ApplicationRecord
#   has_many: recommendations
# end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recommendation

  validates :content, presence: true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  # belongs_to :category

  has_one_attached :image


  validates :name, :image, :location, :description, presence: true

  scope :alpha, -> { order (:name)}
end

app/models/user.rb
class User < ApplicationRecord

  has_many :recommendations
  has_many :comments
  has_many :commented_recommendations, through: :comments, source: :recommendation
  has_secure_password

  validates :username, :email, presence: true
  validates :username, uniqueness: true 

  def self.create_from_omniauth(auth)
    User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
        u.username = auth['info']['first_name']
        u.email = auth['info']['email']
        u.password = SecureRandom.hex(16)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # this gives access to these in the views
  helper_method :current_user, :logged_in?

  private

  def current_user
    # if @current_user isn't already defined it will find by id (and if there is a session id)
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def redirect_if_not_logged_in
    redirect_to root_path if !logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :get_recommendation


  def index
    @comments = @recommendation.comments
  end

  def show
  end

  def new
    @comment = @recommendation.comments.build
    # if it's nested and we find the recommendation
    #if params[:recommendation_id] && @recommendation = Recommendation.find_by_id(params[:recommendation_id])
    #  @comment = @recommendation.comments.build
    #else
    #  @comment = Comment.new
    #end
  end

  def create
    #@comment = @recommendation.comments.build
    @recommendation = Recommendation.find(params[:comment][:recommendation_id])
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to recommendation_comments_path
    else
      render :new
    end
  end


  private

  def set_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def get_recommendation
    @recommendation = Recommendation.find(params[:recommendation_id])
  end

  def comment_params
    params.require(:comment).permit(:title, :content, :recommendation_id)
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :redirect_if_not_logged_in

  def index
    @recommendations = Recommendation.alpha
  end

  def show
    @recommendation = Recommendation.find_by_id(params[:id])
  end

  def new
    @recommendation = Recommendation.new
  end

  def create
    @recommendation = current_user.recommendations.build(recommendation_params)

    if @recommendation.save
      redirect_to recommendation_path(@recommendation)
    else
      render :new
    end
  end

  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  def update
     @recommendation = current_user.recommendations.find(params[:id])

    if @recommendation.update(recommendation_params)
      redirect_to recommendation_path(@recommendation)
    else
      render :edit
    end
  end

  def destroy
    #@recommendation = current_user.recommendations.find(params[:id])
    @recommendation = current_user.recommendations.find(params[:id])
    @recommendation.destroy
    redirect_to recommendations_path
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:name, :image, :location, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #find the user
    user = User.find_by(username: params[:user][:username])
    #authenticate user, if there is a user and they are authenticated
    if user && user.authenticate(params[:user][:password])
      #set session id to user id
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def omniauth
    #find_or_create a user using the attributes from auth
    user = User.create_from_omniauth(auth)

    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_path
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # check to see if user saves
    if @user.save
    # log them in and redirect to show page
       session[:user_id] = @user.id
       redirect_to user_path(@user)
    else
       render :new
    end
  end

  def show
    redirect_if_not_logged_in
    @user = User.find_by_id(params[:id])
    #if it doesn't find id, this will give you nil instead of an error, redirect if no user is found
    redirect_to root_path if !@user
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper

  def recommendation_creator
    @recommendation.user_id === current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>Comments for <%= @recommendation.name %></h1>

<ul>
<% @comments.each do |comment|%>
  <li><p><strong> <%= comment.title %> </strong></p>
      <p>"<%= comment.content%>" by: <%= comment.user.username%>
      <p>About this recommendation: <strong><%= link_to comment.recommendation.name,recommendation_path(comment.recommendation_id) %></strong></p>
  </li>
<% end %>
</ul>

app/views/comments/new.html.erb
<% if @comment.errors %>
  <ul>
    <%  @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <%end%>
  </ul>
<% end %>

<h1>Let us know what you think of <%= @comment.recommendation.name %></h1>

<%= form_for([@comment.recommendation, @comment]) do |f| %>

  <%= f.hidden_field :recommendation_id, :value => @recommendation.id %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <br>

  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <br>

  <%= f.submit %>

<% end %>

app/views/comments/show.html.erb
<h1>Comments for <%= @recommendation.name %></h1>

<ul>
<% @comments.each do |comment|%>
  <li><%= comment.user.username%> says "<%= comment.content%>" about this recommendation: <strong><%= link_to comment.recommendation.name, recommendation_path(comment.recommendation_id) %></strong></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if logged_in? %>
        <%= button_to "Recommendations", recommendations_path, method: :get %>
        <%= button_to "Make a Recommendation", new_recommendation_path, method: :get %>

        <%= button_to "Logout", logout_path, method: "delete" %>
      <% else %>
        <%= button_to "Sign Up", signup_path, method: :get %>
        <%= button_to "Login", login_path, method: :get %>
        <%= button_to "Log In with Google", '/auth/google_oauth2' %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/recommendations/_form.html.erb
<%= form_for(@recommendation) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>

  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <br>

  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <br>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <br>

  <%= f.submit "Submit" %>

<% end %>

app/views/recommendations/edit.html.erb
<h1>Edit this recommendation</h1>

<%= form_for(@recommendation) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>

  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <br>

  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <br>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <br>

  <%= f.submit "Edit" %>

<% end %>

app/views/recommendations/index.html.erb
<h1>All Recommendations</h1>

<div class="recos">
  <div class="container">
    <div class="row">

  <% @recommendations.each do |recommendation| %>
  <div class="col-sm-6">
  <div class ="solo" class="card">
    <div class="card-img-top"> <% if recommendation.image.attached? %> <img src="<%= (url_for(recommendation.image)) %>" alt="<%= recommendation.name %>" width="440px" height="400px"> <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= recommendation.name %></h5>
      <p class="card-text">Location: <%= recommendation.location %><br>
        Description: <%= recommendation.description %>
      </p>
      <% if logged_in? && !recommendation.user_id === current_user.id %>
      <%= button_to "Learn more and Comment", recommendation_path(recommendation), method: :get, class:"buttons" %>
      <% end %>

      <% if logged_in? && recommendation.user_id === current_user.id %>
        <%= button_to "Edit", edit_recommendation_path(recommendation), method: :get, class:"buttons" %>
      <% end %>

      <%= button_to "See Comments", recommendation_comments_path(recommendation), method: :get, class:"buttons" %>
    </div>
  </div>
  </div>

  <% end %>
    </div>
  </div>
</div>

<!-- <div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div> -->

app/views/recommendations/new.html.erb
<% if @recommendation.errors %>
  <ul>
    <%  @recommendation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <%end%>
  </ul>
<% end %>

<h1>Make a New Recommendation</h1>

<%= form_for(@recommendation) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>

  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <br>

  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <br>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <br>

  <%= f.submit "Submit your Recommendation!" %>

<% end %>

app/views/recommendations/show.html.erb
<% if logged_in? &&  recommendation_creator #@recommendation.user_id === current_user.id %>
  <h1>Hey <%= current_user.username %>, nice recommendation!</h1>
<% else %>
  <h1><%= current_user.username %> check this one out!</h1>
<% end %>

<div> <img src="<%= (url_for(@recommendation.image)) %>" alt="<%= @recommendation.name %>" height="300" width="300"> </div>
<h3><%= @recommendation.name %></h3>
<p>Location: <%= @recommendation.location %></p>
<p>Description: <%= @recommendation.description %></p>
<%= link_to "Back", recommendations_path %>

<% if logged_in? &&  recommendation_creator #@recommendation.user_id === current_user.id %>
  <%= link_to "Edit", edit_recommendation_path(@recommendation) %>
  <%= link_to "Delete", recommendation_path(@recommendation), method: :delete %>
<% else %>
  <%= link_to "Comment!", new_recommendation_comment_path(@recommendation) %>
<% end %>

app/views/users/new.html.erb
<% if @user.errors %>
  <ul>
    <%  @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <%end%>
  </ul>
<% end %>

<h1>Sign Up</h1>

<%= form_for(@user, url:'/signup') do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <br>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %></h1>